name: Preview a terraform plan
run-name: Preview ${{ inputs.infra }} terraform plan
permissions:
  id-token: write
  contents: read
on:
  workflow_call:
    inputs:
      infra:
        type: string
        description: Infrastructure directory to preview
        required: true

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Authenticate with IAM
        uses: terramaps/terramaps-infra/.github/actions/iam-auth@main
      - name: Checkout
        uses: actions/checkout@v4
      - uses: hashicorp/setup-terraform@v3
      - name: Preview terraform plan
        run: |
          terraform -chdir=${{ inputs.infra }} init
          terraform -chdir=${{ inputs.infra }} plan -detailed-exitcode
